#! /bin/sh

bspc config border_width        2
bspc config window_gap          36 

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor VGA-1  -d VI VII VIII IX X
bspc monitor DP-1 -d I II III IV V

bspc rule -a Icedove desktop=^2 floating=on
bspc rule -a Gimp follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a xclock floating=on desktop=^6
bspc rule -a psensor floating=on
bspc rule -a caja floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Startup programs
#panel &
xscreensaver -no-splash &
icedove &
xclock -d -update 1 -chime &
dropbox start


