#! /bin/sh
# big shoutout to github.com/easysid for the inspiration 

# config
bspc config border_width          2
bspc config window_gap            10 
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config auto_cancel           true

# monitors & desktops
bspc monitor VGA-1  -d VI VII VIII IX X
bspc monitor DP-1 -d I II III IV V
bspc desktop ^9 -t floating=on
bspc desktop ^10 -t floating=on
bspc config -m VGA-1 right_padding 220 # make room for conky

# rules
bspc rule -a Icedove desktop=^10 
bspc rule -a Gimp follow=on floating=on
bspc rule -a caja floating=on
bspc rule -a lxappearance floating=on center=true
bspc rule -a nitrogen floating=on center=true
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# colors
bspc config focused_border_color "#1d1f21"
bspc config active_border_color "#1d1f21" 
bspc config normal_border_color "#1d1f21"
bspc config focused_locked_border_color "#a54242"
bspc config active_locked_border_color "#373b41"
bspc config normal_locked_border_color"#373b41"
bspc config urgent_border_color "#de935f"
bspc config presel_border_color "#de935f"

# startup programs
xscreensaver -no-splash &
compton --shadow-exclude '!focused' &
nitrogen --restore
conky &
numlockx &
icedove &
dropbox start &
mpd &
